# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            love4src
tagline:          'Software is eating the world'
description:      'Opinionated discussions of people making software.'
url:              https://www.love4src.com
baseurl:          https://www.love4src.com/

author:
  name:           'Y Experiment'
  url:            https://www.yexperiment.com

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/yexperiment/love4src
