# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            love4src
tagline:          'Software is eating the world'
description:      'Opinionated discussions of people making software.'
url:              https://www.love4src.com
baseurl:          /

author:
  name:           'Y Experiment'
  url:            https://www.yexperiment.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/yexperiment/love4src
